from IPython.core.display import display, Markdown

def __init__():
    pass

def display_description(reason_code):
    display(Markdown(f"{reason_code} : {reason_map[reason_code]}"))
    
reason_map = {
"A11"  : "... < 0 DM (Status of existing checking account)",
"A12"  : "0 <= ... < 200 DM (Status of existing checking account)",
"A13"  : "... >= 200 DM / salary assignments for at least 1 year (Status of existing checking account)",
"A14"  : "no checking account (Status of existing checking account)",
"A30"  : "no credits taken/ all credits paid back duly (Credit history)",
"A31"  : "all credits at this bank paid back duly (Credit history)",
"A32"  : "existing credits paid back duly till now (Credit history)",
"A33"  : "delay in paying off in the past (Credit history)",
"A34"  : "critical account/ other credits existing (not at this bank) (Credit history)",
"A40"  : "car (new) ",
"A41"  : "car (used) ",
"A42"  : "furniture/equipment ",
"A43"  : "radio/television ",
"A44"  : "domestic appliances ",
"A45"  : "repairs ",
"A46"  : "education ",
"A47"  : "(vacation - does not exist?) ",
"A48"  : "retraining ",
"A49"  : "business ",
"A410" : "others ",
"A61"  : "... < 100 DM (Savings account/bonds)",
"A62"  : "100 <= ... < 500 DM (Savings account/bonds)",
"A63"  : "500 <= ... < 1000 DM (Savings account/bonds)",
"A64"  : ".. >= 1000 DM (Savings account/bonds)",
"A65"  : "unknown/ no savings account (Savings account/bonds)",
"A71"  : "unemployed ",
"A72"  : "... < 1 year (Present employment)",
"A73"  : "1 <= ... < 4 years (Present employment)",
"A74"  : "4 <= ... < 7 years (Present employment)",
"A75"  : ".. >= 7 years (Present employment)",
"A91"  : "male : divorced/separated ",
"A92"  : "female : divorced/separated/married ",
"A93"  : "male : single ",
"A94"  : "male : married/widowed ",
"A95"  : "female : single ",
"A101" : "No Other debtors / guarantors",
"A102" : "co-applicant ",
"A103" : "guarantor ",
"A121" : "real estate ",
"A122" : "if not A121 : building society savings agreement/ life insurance ",
"A123" : "if not A121/A122 : car or other, not in attribute 6 ",
"A124" : "unknown / no property ",
"A141" : "bank (installment plans)",
"A142" : "stores (installment plans)",
"A143" : "none (installment plans)",
"A151" : "rent",
"A152" : "own house ",
"A153" : "does not rent or own",
"A171" : "unemployed/ unskilled - non-resident ",
"A172" : "unskilled - resident ",
"A173" : "skilled employee / official ",
"A174" : "management/ self-employed/ highly qualified employee/ officer ",
"A191" : "no telephone",
"A192" : "yes, telephone registered under the customers name ",
"A201" : "is foreign worker ",
"A202" : "is not foreign worker" }